version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: stock_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock_analysis_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
      - ./src/db/mysql_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
volumes:
  db_data:
